version: '3'
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  app: &app_base
    build: .
    volumes:
      - .:/app
      - ./vendor/bundle:/app/vendor/bundle:delegated
      - ./node_modules:/app/node_modules:delegated
    tty: true
    stdin_open: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    tmpfs:
      - /app/tmp/pids
    depends_on:
      - db
      - webpack
    env_file:
      - docker.env
  webpack:
    <<: *app_base
    command: bin/webpack-dev-server
    ports:
      - "3035:3035"
    depends_on:
      - db
volumes:
  db:
    driver: local
